// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserRepository = "user_repository"

// UserRepository mapped from table <user_repository>
type UserRepository struct {
	ID                 int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Identity           string         `gorm:"column:identity" json:"identity"`
	UserIdentity       string         `gorm:"column:user_identity" json:"user_identity"`
	ParentID           int64          `gorm:"column:parent_id" json:"parent_id"`
	RepositoryIdentity string         `gorm:"column:repository_identity" json:"repository_identity"`
	Ext                string         `gorm:"column:ext" json:"ext"` // 文件或文件夹类型
	Name               string         `gorm:"column:name" json:"name"`
	CreatedAt          time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserRepository's table name
func (*UserRepository) TableName() string {
	return TableNameUserRepository
}
