// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserBasic = "user_basic"

// UserBasic mapped from table <user_basic>
type UserBasic struct {
	ID          int            `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Identity    string         `gorm:"column:identity" json:"identity"`
	Name        string         `gorm:"column:name" json:"name"`
	Password    string         `gorm:"column:password" json:"password"`
	Email       string         `gorm:"column:email" json:"email"`
	NowVolume   int64          `gorm:"column:now_volume" json:"now_volume"`     // 已使用容量
	TotalVolume int64          `gorm:"column:total_volume" json:"total_volume"` // 总容量
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UserBasic's table name
func (*UserBasic) TableName() string {
	return TableNameUserBasic
}
